spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/weather;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    batch:
      initialize-schema: always

  serviceKey : kQkDPvw2TDmPAFD7HvgUb31WyyKpPrzI%2BH%2BXoELvejXjWxJb1H5gIaZAdwhv%2FjuqyJ9OSdPYQYSCKhKEp3E7TA%3D%3D


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
