spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/weather
    username: sa
    password:
    driver-class-name: org.h2.Driver
    batch:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true